# Generated by Django 3.0.5 on 2020-05-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('level1', models.CharField(max_length=50)),
                ('level2', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('keywords', models.CharField(max_length=1000)),
                ('picture', models.FileField(upload_to='')),
                ('id_required', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('critical_val', models.PositiveSmallIntegerField()),
                ('current_holders', models.CharField(max_length=1000)),
                ('is_consumable', models.BooleanField(default=False)),
                ('colour_code', models.CharField(max_length=10)),
                ('notifications', models.CharField(max_length=10000)),
                ('price', models.PositiveIntegerField()),
                ('flag', models.BooleanField(default=False)),
                ('flag_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Item')),
            ],
        ),
    ]
