# Generated by Django 3.0.5 on 2020-05-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20200523_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='time',
        ),
    ]
