# Generated by Django 3.0.5 on 2020-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20200527_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='colour_code',
            field=models.CharField(default='green', max_length=20),
            preserve_default=False,
        ),
    ]
