# Generated by Django 3.0.5 on 2020-05-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20200528_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='colour_code',
        ),
    ]
