# Generated by Django 3.0.5 on 2020-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_auto_20200528_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
