# Generated by Django 3.0.5 on 2020-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20200603_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
