# Generated by Django 3.0.5 on 2020-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20200606_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
