# Generated by Django 3.0.5 on 2020-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20200609_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
    ]
