# Generated by Django 3.0.5 on 2020-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_auto_20200609_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
