# Generated by Django 3.0.5 on 2020-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20200613_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='Thank you for registering to our site')),
                ('message', models.TextField(default=' it  means a world to us ')),
                ('recipient_list', models.TextField(default="['tanmay.v.hiremath@gmail.com']")),
            ],
        ),
    ]
