# Generated by Django 3.0.5 on 2020-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20200613_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='current_holders',
        ),
        migrations.RemoveField(
            model_name='item',
            name='displaylevel1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='displaylevel2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='request',
            name='colour_code',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
    ]
