# Generated by Django 3.0.5 on 2020-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='refresh_code',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='customer',
            name='refresh_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='html_message',
            field=models.TextField(default='<h1>default</h1>'),
        ),
    ]
