# Generated by Django 3.0.5 on 2020-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_auto_20200615_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='auth_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='customer',
            name='program_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='roll_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='recipient_list',
            field=models.TextField(default='[tanmay.v.hiremath@gmail.com]'),
        ),
    ]
