# Generated by Django 3.0.5 on 2020-06-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_auto_20200616_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
