# Generated by Django 3.0.5 on 2020-06-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_remove_customer_user'),
        ('tools', '0021_auto_20200616_0044'),
    ]

    operations = [
    ]
