# Generated by Django 3.0.5 on 2020-06-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
