# Generated by Django 3.0.5 on 2020-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20200616_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='roll_number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
