# Generated by Django 3.0.5 on 2020-06-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20200616_2131'),
        ('tools', '0030_customer_last_name'),
    ]

    operations = [
    ]
