# Generated by Django 3.0.5 on 2020-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0032_auto_20200617_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='id',
        ),
        migrations.AddField(
            model_name='mail',
            name='roll_number',
            field=models.CharField(default='123456789', max_length=11, primary_key=True, serialize=False),
        ),
    ]
