# Generated by Django 3.0.5 on 2020-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0033_auto_20200618_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='recipient_list',
            field=models.TextField(default="['tanmay.v.hiremath@gmail.com']"),
        ),
    ]
