# Generated by Django 3.0.5 on 2020-06-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0037_auto_20200618_1644'),
        ('tools', '0031_merge_20200617_2043'),
    ]

    operations = [
    ]
