# Generated by Django 3.0.5 on 2020-06-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0038_merge_20200618_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='roll',
            new_name='roll_number',
        ),
    ]
