# Generated by Django 3.0.5 on 2020-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0039_auto_20200622_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
