# Generated by Django 3.0.7 on 2020-07-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0039_auto_20200622_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='roll_number',
            field=models.CharField(default='19D070003', max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flag',
            name='roll_number',
            field=models.ForeignKey(default='19D070003', on_delete=django.db.models.deletion.CASCADE, to='tools.Customer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.TextField(default='It means the world to us'),
        ),
        migrations.AlterField(
            model_name='request',
            name='roll_number',
            field=models.ForeignKey(default='19D070003', on_delete=django.db.models.deletion.CASCADE, to='tools.Customer'),
        ),
    ]
