# Generated by Django 3.0.5 on 2020-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0041_auto_20200719_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='issued_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
