# Generated by Django 3.0.5 on 2020-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0042_auto_20200719_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='returned_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
