# Generated by Django 3.0.5 on 2020-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0043_auto_20200719_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
