# Generated by Django 3.0.7 on 2020-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0045_request_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='checkout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='issued_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='returned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
