# Generated by Django 3.0.7 on 2020-08-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0050_itemcategory_machinecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='level1',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='item',
            name='level2',
        ),
    ]
