# Generated by Django 3.0.7 on 2020-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0051_auto_20200801_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='machinecategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machinecategory',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
